apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "structurizr.fullname" . }}-properties-cm
  labels:
    {{- include "structurizr.labels" . | nindent 4 }}
data:
  structurizr_properties: |-
{{- .Values.structurizr_properties | nindent 6 }}
